oc_comments:
    resource: "@OCCommentsBundle/Resources/config/routing.yml"
    prefix:   /

oc_community:
    resource: "@OCCommunityBundle/Resources/config/routing.yml"
    prefix:   /

oc_core:
    resource: "@OCCoreBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
